"""Embed the existing controller SVG sprites for the standalone keyboard NRO."""
from pathlib import Path
import hashlib
import io
import struct
import cairosvg
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
NAMES=('A','B','X','Y','L','R','SL','SR','Plus','Minus')

def main():
    lines=['/* Generated by tools/build-fextendo-osk-sprites.py from the existing',
           ' * Solid Duo controller artwork. See assets/README.md for attribution. */',
           '#ifndef FEXTENDO_OSK_SPRITES_H','#define FEXTENDO_OSK_SPRITES_H',
           '#include <stdint.h>','enum { '+', '.join('FX_OSK_SPRITE_'+n.upper() for n in NAMES)+' };',
           '#define FX_OSK_SPRITE_SIZE 40','static const uint32_t fx_osk_sprites[10][1600] = {']
    for name in NAMES:
        path=ROOT/f'assets/Solid Duo/Dark theme/{name}_Button.svg'
        image=Image.open(io.BytesIO(cairosvg.svg2png(bytestring=path.read_bytes(),output_width=160,output_height=160))).convert('RGBA')
        pixels=image.resize((40,40),Image.Resampling.LANCZOS).tobytes()
        values=struct.unpack('<1600I',pixels)
        lines.append('/* '+name+' source SHA256 '+hashlib.sha256(path.read_bytes()).hexdigest()+' */\n{')
        for i in range(0,len(values),10):lines.append(','.join(f'0x{v:08x}' for v in values[i:i+10])+',')
        lines.append('},')
    lines+=['};','#endif','']
    (ROOT/'src/runtime/fextendo_osk_sprites.h').write_text('\n'.join(lines))

if __name__=='__main__':main()
