"""Generate a compiled repair allowlist from an independently pinned release ZIP."""
import argparse
import hashlib
import json
from pathlib import Path
import stat
import zipfile

TAG = 'v0.3.8-r9'
ASSET = 'FEXTendo-v0.3.8-r9-sd.zip'
SHA = '40ca7020d05aabc61420fab447d1486b5cb597833ba5d72ae3e295712c61c9f3'
PREFIX = 'switch/pes13-fex/'


def allowed(path):
    # Runtime-owned immutable files only. Renderer choice, active d3d9.dll,
    # settings.dat, user profiles/registry, game files and NRO are excluded.
    return (path.startswith(('drive_c/windows/system32/', 'drive_c/windows/syswow64/')) and path.endswith('.dll')
            or path.startswith('share/wine/nls/') and path.endswith('.nls')
            or path.startswith(('drive_c/windows/fonts/', 'share/wine/fonts/')) and path.endswith(('.ttf', '.fon'))
            or path in ('launcher/renderers/dxvk-3.1.1/d3d9.dll', 'launcher/renderers/dxvk-3.1.1/dxvk.conf',
                        'launcher/renderers/dxvk-2.7.1-async/d3d9.dll', 'launcher/renderers/dxvk-2.7.1-async/dxvk.conf'))


def generate(archive, out):
    digest = lambda b: hashlib.sha256(b).hexdigest()
    raw = archive.read_bytes()
    if digest(raw) != SHA:
        raise ValueError('Expected the published r9 package hash')
    files = []
    with zipfile.ZipFile(archive) as z:
        if len(z.namelist()) != len(set(z.namelist())):
            raise ValueError('Duplicate ZIP entry')
        manifest = json.loads(z.read('manifest.json'))
        if manifest['package_version'] != TAG or manifest['runtime_version'] != '0.3.8-r6':
            raise ValueError('Incompatible runtime')
        for info in z.infolist():
            if not info.filename.startswith(PREFIX) or info.is_dir():
                continue
            name = info.filename[len(PREFIX):]
            if not allowed(name):
                continue
            if ('..' in name.split('/') or '\\' in name or ':' in name or stat.S_ISLNK(info.external_attr >> 16)):
                raise ValueError('Invalid member')
            data = z.read(info)
            if digest(data) != manifest['files'][info.filename] or len(data) > 64 * 1024 * 1024:
                raise ValueError('Invalid runtime member')
            files.append((name, len(data), digest(data)))
    files.sort()
    if not any(n == 'drive_c/windows/system32/libwow64fex.dll' for n, _, _ in files):
        raise ValueError('Missing FEX')
    identity = digest(json.dumps(files, separators=(',', ':')).encode())
    lines = ['/* Generated by tools/runtime_fixer_catalog.py; do not edit. */',
             '#define FXR_COUNT ' + str(len(files)), '#define FXR_CATALOG_ID "' + identity + '"',
             '#define FXR_ARCHIVE_SHA "' + SHA + '"', '#define FXR_ARCHIVE_SIZE ' + str(len(raw)) + 'ull',
             '#define FXR_URL "https://github.com/Ibnuard/pes13_nx/releases/download/' + TAG + '/' + ASSET + '"',
             'static const struct fxr_file fxr_files[FXR_COUNT] = {']
    lines += ['    {' + json.dumps(n) + ',' + str(size) + 'ull,"' + sha + '"},' for n, size, sha in files]
    out.write_text('\n'.join(lines + ['};', '']), encoding='utf-8', newline='\n')
    print(json.dumps({'files': len(files), 'bytes': sum(size for _, size, _ in files), 'catalog': identity}))


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('archive', type=Path)
    p.add_argument('output', type=Path)
    a = p.parse_args()
    generate(a.archive, a.output)
